#cloud-config

# /var/lib/rancher/conf/cloud-config.d/nfs.yml

# https://github.com/rancher/os/issues/641
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    content: |
      #!/bin/bash
      [ ! -e /usr/bin/docker ] && ln -s /usr/bin/docker.dist /usr/bin/docker

rancher:
  services:
    nfs-movies:
      image: walkerk1980/rancher-nfs-client
      labels:
        io.rancher.os.after: console, preload-user-images
        io.rancher.os.scope: system
      net: host
      privileged: true
      restart: always
      volumes:
      - /usr/bin/iptables:/sbin/iptables:ro
      - /mnt/nfs-movies:/mnt/nfs-movies:shared
      environment:
        SERVER: 192.168.1.186
        SHARE: /mnt/Valhalla/Media/Movies
        MOUNTPOINT: /mnt/nfs-movies

    nfs-tv:
      image: walkerk1980/rancher-nfs-client
      labels:
        io.rancher.os.after: console, preload-user-images
        io.rancher.os.scope: system
      net: host
      privileged: true
      restart: always
      volumes:
      - /usr/bin/iptables:/sbin/iptables:ro
      - /mnt/nfs-tv:/mnt/nfs-tv:shared
      environment:
        SERVER: 192.168.1.186
        SHARE: /mnt/Improbability/Media/tv
        MOUNTPOINT: /mnt/nfs-tv

    nfs-anime:
      image: walkerk1980/rancher-nfs-client
      labels:
        io.rancher.os.after: console, preload-user-images
        io.rancher.os.scope: system
      net: host
      privileged: true
      restart: always
      volumes:
      - /usr/bin/iptables:/sbin/iptables:ro
      - /mnt/nfs-anime:/mnt/nfs-anime:shared
      environment:
        SERVER: 192.168.1.186
        SHARE: /mnt/Improbability/Media/Anime
        MOUNTPOINT: /mnt/nfs-anime
