#cloud-config

# /var/lib/rancher/conf/cloud-config.d/nfs.yml

# https://github.com/rancher/os/issues/641
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    content: |
      #!/bin/bash
      [ ! -e /usr/bin/docker ] && ln -s /usr/bin/docker.dist /usr/bin/docker

rancher:
  services:
    nfs-Val:
      image: walkerk1980/rancher-nfs-client
      labels:
        io.rancher.os.after: console, preload-user-images
        io.rancher.os.scope: system
      net: host
      privileged: true
      restart: always
      volumes:
      - /usr/bin/iptables:/sbin/iptables:ro
      - /mnt/nfs-Val:/mnt/nfs-Val:shared
      environment:
        SERVER: 192.168.1.186
        SHARE: /mnt/Valhalla/Media
        MOUNTPOINT: /mnt/nfs-Val

    nfs-Imp:
      image: walkerk1980/rancher-nfs-client
      labels:
        io.rancher.os.after: console, preload-user-images
        io.rancher.os.scope: system
      net: host
      privileged: true
      restart: always
      volumes:
      - /usr/bin/iptables:/sbin/iptables:ro
      - /mnt/nfs-Imp:/mnt/nfs-Imp:shared
      environment:
        SERVER: 192.168.1.186
        SHARE: /mnt/Improbability/Media
        MOUNTPOINT: /mnt/nfs-Imp
